### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by rasky** [RenaKunisaki/64drive-usb-linux#3]
Is this tool still maintained? I found several bugs last I tested it on my 64drive HW2, but there has not been any recent activity. I wrote my own tool (https://github.com/rasky/g64drive) which has grown to be more complete. Should this one be archived and users pointed to g64drive which is actively maintained?

**Comment by RenaKunisaki** [comment]
I wish you would have reported the bugs... anyway yeah it's probably best to just direct people to yours.
